import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers/Index";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Credilider app",
  description: "Generated by Leancore",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body >
        <Providers>
          {children}
        </Providers>
      </body>
    {/*   <footer style={{ display: 'flex', justifyContent: 'center', padding:'1em' }}>
        <p>&copy; 2024 Credilider. All rights reserved.</p>
      </footer> */}
    </html>
  );
}
