import { Amplify } from 'aws-amplify';

import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/Providers";
import { getAwsConfig } from '@/auth/AuthProvider/aws-exports';

async function configureAmplify() {
  const config = await getAwsConfig();
  Amplify.configure(config);
}

configureAmplify();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Credilider app",
  description: "Generated by Leancore",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body >    
        <Providers>
          {children}
        </Providers>     
      </body>
  
    </html>
  );
}


/* import { AuthProvider } from '@/context/AuthContext'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
} */
